// Type definitions for p5.tween
// Project: p5.tween
// Definitions by: Generated by Copilot

declare namespace p5.tween {
  /**
   * Easing functions available in p5.tween.
   * Each function takes a normalized time (t: number, 0-1) and returns a number.
   */
  const EASINGS: {
    /** No easing, no acceleration */
    linear: (t: number) => number;
    /** Accelerating from zero velocity */
    easeInQuad: (t: number) => number;
    /** Decelerating to zero velocity */
    easeOutQuad: (t: number) => number;
    /** Acceleration until halfway, then deceleration */
    easeInOutQuad: (t: number) => number;
    /** Accelerating from zero velocity */
    easeInCubic: (t: number) => number;
    /** Decelerating to zero velocity */
    easeOutCubic: (t: number) => number;
    /** Acceleration until halfway, then deceleration */
    easeInOutCubic: (t: number) => number;
    /** Accelerating from zero velocity */
    easeInQuart: (t: number) => number;
    /** Decelerating to zero velocity */
    easeOutQuart: (t: number) => number;
    /** Acceleration until halfway, then deceleration */
    easeInOutQuart: (t: number) => number;
    /** Accelerating from zero velocity */
    easeInQuint: (t: number) => number;
    /** Decelerating to zero velocity */
    easeOutQuint: (t: number) => number;
    /** Acceleration until halfway, then deceleration */
    easeInOutQuint: (t: number) => number;
    /** Elastic bounce effect at the beginning */
    easeInElastic: (t: number) => number;
    /** Elastic bounce effect at the end */
    easeOutElastic: (t: number) => number;
    /** Elastic bounce effect at the beginning and end */
    easeInOutElastic: (t: number) => number;
    /** Sine wave easing in */
    easeInSin: (t: number) => number;
    /** Sine wave easing out */
    easeOutSin: (t: number) => number;
    /** Sine wave easing in and out */
    easeInOutSin: (t: number) => number;
  };

  /**
   * Tween animates numeric properties of an object over time using keyframes and easing functions.
   */
  class Tween {
    /**
     * Creates a new Tween for the given object.
     * @param objStart The object whose properties will be animated.
     */
    constructor(objStart: any);

    /**
     * Adds a new motion (keyframe) to the tween.
     * @param key The property name to animate.
     * @param target The target value for the property.
     * @param duration Duration of the motion in milliseconds.
     * @param easing Name of the easing function (default: 'linear').
     */
    addMotion(key: string, target: number, duration: number, easing?: string): Tween;

    /**
     * Adds a new combined motion to the tween (multiple properties animated together).
     * @param actions Array of { key, target } pairs.
     * @param duration Duration of the motion in milliseconds.
     * @param easing Name of the easing function (default: 'linear').
     */
    addMotions(actions: { key: string; target: number }[], duration: number, easing?: string): Tween;

    /**
     * Removes all motions from this tween.
     */
    resetMotions(): void;

    /**
     * Starts the tween and plays it in a loop.
     */
    startLoop(): Tween;

    /**
     * Starts the tween and plays it once.
     */
    startTween(): Tween;

    /**
     * Pauses the tween at its current state.
     */
    pause(): Tween;

    /**
     * Resumes the tween from its paused state.
     */
    resume(): Tween;

    /**
     * Restarts the tween from the beginning.
     */
    restart(): Tween;

    /**
     * Updates the tween's state. Should be called with the time since last update.
     * @param deltaTime Time in milliseconds since last update.
     */
    update(deltaTime: number): void;

    /**
     * Sets a function to be called when the tween ends.
     * @param listener Function called with the tween instance as argument.
     */
    onEnd(listener: (tween: Tween) => void): Tween;

    /**
     * Sets a function to be called every time the tween completes a loop.
     * @param listener Function called with the tween instance as argument.
     */
    onLoop(listener: (tween: Tween) => void): Tween;
  }

  /**
   * GeometricObjectTween is a Tween specialized for geometric objects (x, y, width, height, etc).
   */
  class GeometricObjectTween extends Tween {
    /**
     * Adds a motion for multiple geometric properties at once.
     * @param object Object with any of x, y, width, height, w, h, angle, rotation.
     * @param duration Duration of the motion in milliseconds.
     * @param easing Name of the easing function (default: 'linear').
     */
    addMotionTo(
      object: {
        x?: number;
        y?: number;
        width?: number;
        height?: number;
        w?: number;
        h?: number;
        angle?: number;
        rotation?: number;
      },
      duration: number,
      easing?: string
    ): void;
  }

  /**
   * TweenManager manages multiple tweens and updates them together.
   */
  class TweenManager {
    /**
     * Returns the Tween with the given name.
     * @param name The name of the Tween.
     */
    getTween(name: string): Tween;

    /**
     * Adds a new Tween to the manager and returns it.
     * @param object The object to animate.
     * @param name The name for this Tween.
     */
    addTween(object: any, name: string): Tween;

    /**
     * Updates all tweens managed by this manager.
     * @param deltaTime Time in milliseconds since last update.
     */
    update(deltaTime: number): void;
  }

  /**
   * The default TweenManager instance used by p5.tween.
   */
  const manager: TweenManager;
}
